FACENET:
  model: "20180402-114759"
  #image_size: 160
  #margin: 44
  #gpu_mem_fraction: 1.0
OPENPOSE:
  # Debugging/Other
  logging_level: 3
  disable_multi_thread: false
  profile_speed: 1000
  # OpenPose
  model_folder: "models/"
  prototxt_path: ""
  caffemodel_path: ""
  output_resolution: "-1x-1"
  num_gpu: -1
  num_gpu_start: 0
  keypoint_scale: 0
  number_people_max: -1
  maximize_positives: false
  fps_max: -1.
  # OpenPose Body Pose
  body: 1
  model_pose: "BODY_25"
  net_resolution: "-1x368"
  scale_number: 1
  scale_gap: 0.25