version: 1
disable_existing_loggers: False

formatters:
    default:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
        datefmt: "%Y/%m/%d %H:%M:%S"
    ros_fmt:
      format: "[%(name)s][%(levelname)s] %(asctime)s: %(message)s"


handlers:
    console:
        class: logging.StreamHandler
        formatter: default
        level: DEBUG
        stream: ext://sys.stdout
    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: default
        filename: info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8
    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: WARNING
        formatter: default
        filename: errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8
    rosconsole:
        class: rosgraph.roslogging.RosStreamHandler
        level: DEBUG
        formatter: ros_fmt
        colorize: True

loggers:
    face_recognition_ros:
        level: DEBUG
        handlers: [console, info_file_handler, error_file_handler]
        propagate: no
        qualname: face_recognition_ros
    rosout:
        level: INFO
        handlers: [rosconsole]
        propagate: yes
        qualname: rosout
        colorize: True

root:
    level: DEBUG
    handlers: [console, info_file_handler, error_file_handler, rosconsole]