#!/usr/bin/env python2

# import rospy
import numpy as np 

import tensorflow as tf

from face_recognition_ros import face_encoding
from utils import embedings, files



if __name__ == "__main__":
    test_images = files.get_flw_sample_path([1, 1], [0, 1])

    with tf.Graph().as_default():
        with tf.Session() as sess:
            det = face_encoding.FacialEncoder(sess, "20180402-114759.pd")
            images = face_encoding.load_images(test_images)
            mat = embedings.compare_images(det.predict(images))
            embedings.plot_comp_matrix(mat)
