#!/usr/bin/env python2
from __future__ import print_function

import sys
import os
from os import path
import argparse

import tensorflow as tf

from utils import files
from face_recognition_ros import face_encoding, face_matching

sample_people = [
    'George_W_Bush',
    'Colin_Powell',
    'Tony_Blair',
    'Donald_Rumsfeld',
    'Gerhard_Schroeder'
    ]


def main(argv):
    with tf.Graph().as_default():
        with tf.Session() as sess:
            enc = face_encoding.FacialEncoder(sess)
            db = face_matching.FaceDatabase(5)
            for di in argv.image_dirs:
                db.add_identity(di, enc)

            db.save(argv.output)
    return


def parse_arguments(argv):
    parser = argparse.ArgumentParser()

    parser.add_argument("-s", "--sample",
                        action="store_true", default=False,
                        help="Load sample images in dataset")
    parser.add_argument("-o", "--output",
                        required=True, help="Output directory")
    parser.add_argument("image_dirs",
                        nargs="*",
                        help="Directories for each person")

    args = parser.parse_args(argv)

    if args.sample:
        for idx, name in enumerate(sample_people):
            sample_people[idx] = files.get_flw_path(name)
        args.image_dirs = sample_people
    elif len(args.image_dirs) == 0:
        parser.error("At least 1 image_dirs is necesary when --sample not enabled.")
    else:
        for i in args.image_dirs:
            parser.error("{} is not a directory".format(i))

    if not path.isdir(args.output):
        parser.error("{} is not a directory".format(args.output))

    return args

if __name__ == "__main__":
    argv = parse_arguments(sys.argv[1:])
    main(argv)
